config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to => 'entries#index'

  resources :entries do
    resources :activities
  end

  resources :entries do
    resources :foods
  end
  
end

app/models/activity.rb
class Activity < ActiveRecord::Base
  belongs_to :entry

  validates :step, :presence => true
  validates :calorie, :presence => true
  validates :minute, :presence => true  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  has_many :activities
  belongs_to :user
  has_many :foods

  validates :day, :presence => true
end

app/models/food.rb
class Food < ActiveRecord::Base
  belongs_to :entry

  validates :item, :presence => true
  validates :calorie, :presence => true
  validates :measurment, :presence => true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :entries
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  def new
    @entry = Entry.find(params[:entry_id])
    @activity = @entry.activities.new
    respond_to do |format|
      format.html { render :new }
      format.js
    end
  end

  def create
    @entry = Entry.find(params[:entry_id])
    @activity = @entry.activities.new(activity_params)
    if @activity.save
      flash[:notice] = "Your activity has been added!"
      redirect_to entry_path(@activity.entry)
    else
      render :new
    end
  end

  def edit
    @entry = Entry.find(params[:entry_id])
    @activity = Activity.find(params[:id])
  end

  def destroy
    @activity = Activity.find(params[:id])
    @activity.destroy
    flash[:notice] = "Your activity has been deleted!"
    redirect_to entry_path(@activity.entry)
  end

  def update
    @entry = Entry.find(params[:entry_id])
    @activity = Activity.find(params[:id])
    if @activity.update(activity_params)
      flash[:notice] = "Your activity has been edited!"
      redirect_to entry_path(@activity.entry)
    else
      render :edit
    end
  end

private
  def activity_params
    params.require(:activity).permit(:step, :calorie, :minute)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_filter :authenticate_user!

  def index
    @entries = Entry.all
    @entries = Entry.order(params[:sort])
  end

  def show
    @entry = Entry.find(params[:id])
  end

  def new
    @entry = Entry.new
    respond_to do |format|
      format.html { render :new }
      format.js
    end
  end

  def create
    @entry = Entry.new(entry_params)
    @entry.user = current_user
    if @entry.save
      flash[:notice] = "Entry successfully added!"
      redirect_to entries_path
    else
      render :new
    end
  end

  def edit
    @entry = Entry.find(params[:id])
    respond_to do |format|
      format.html { render :edit }
      format.js
    end
  end

  def update
    @entry = Entry.find(params[:id])
    if @entry.update(entry_params)
      flash[:notice] = "Entry successfully edited!"
      redirect_to entries_path
    else
      render :edit
    end
  end

  def destroy
    @entry = Entry.find(params[:id])
    @entry.destroy
    flash[:notice] = "Entry successfully deleted!"
    redirect_to entries_path
  end

private
  def entry_params
    params.require(:entry).permit(:day)
  end

end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def new
    @entry = Entry.find(params[:entry_id])
    @food = @entry.foods.new
    respond_to do |format|
      format.html { render :new }
      format.js
    end
  end

  def create
    @entry = Entry.find(params[:entry_id])
    @food = @entry.foods.new(food_params)
    if @food.save
      flash[:notice] = "Your food has been added!"
      redirect_to entry_path(@food.entry)
    else
      render :new
    end
  end

  def edit
    @entry = Entry.find(params[:entry_id])
    @food = Food.find(params[:id])
  end

  def destroy
    @food = Food.find(params[:id])
    @food.destroy
    flash[:notice] = "Your food has been deleted!"
    redirect_to entry_path(@food.entry)
  end

  def update
    @entry = Entry.find(params[:entry_id])
    @food = Food.find(params[:id])
    if @food.update(food_params)
      flash[:notice] = "Your food has been edited!"
      redirect_to entry_path(@food.entry)
    else
      render :edit
    end
  end

  private
    def food_params
      params.require(:food).permit(:item, :calorie, :measurment)
    end

  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/activities/_form.html.erb
<%= render('layouts/errors', :object => @activity) %>

<%= form_for [@entry, @activity], remote: true do |f| %>
  <%= f.label :step %>
  <%= f.number_field :step, class: "form-control" %>
  <%= f.label :calorie %>
  <%= f.number_field :calorie, class: "form-control" %>
  <%= f.label :minute %>
  <%= f.number_field :minute, class: "form-control" %>
  <br>
  <p><%= f.submit class: "btn btn-primary" %></p>
<% end %>

app/views/activities/edit.html.erb
<h1>Edit Activity</h1>

<%= render "form" %>

app/views/activities/edit.js.erb
$("#edit_activity_link").hide().after("<%= j render('form')%>")

app/views/activities/new.html.erb
<h2>New activity for <%= @entry.day %></h2>

<%= render 'form' %>

app/views/activities/new.js.erb
$("#new_activity_link").hide().after("<%= j render('form')%>")

app/views/entries/_form.html.erb
<%= render "layouts/errors", :object => @entry %>

<%= form_for @entry, remote: true do |f| %>
  <%= f.label :day %>
  <%= f.date_field :day, class: "form-control"  %>
  <br>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/entries/edit.html.erb
<!-- <% content_for(:navbar) do %>
  <li><a href="/">Home</a></li>
  <li><%= link_to "Sign In", user_session_path %></li>
  <li><%= link_to "Sign Out", destroy_user_session_path, :method => "delete" %></li>
<% end %> -->

<h2>Edit Entry</h2>

<%= render "form" %>

app/views/entries/edit.js.erb
$('#edit_entry_link').hide().after('<%= j render("form") %>')

app/views/entries/index.html.erb
<h2>Entries</h2>

<table>
  <tr>
    <th>
      <%= link_to "Sort Entries", :sort => "day"%>
    </th>
  </tr>
  <tr>
    <% @entries.each do |entry| %>
    <li><%= link_to entry.day, entry_path(entry) %></li>
    <% end %>
  </tr>
</table>

<%= link_to "New Entry", new_entry_path, id: "new_entry_link", remote: true %>
<hr>
<%= image_tag "yoda.jpg" %>

app/views/entries/new.html.erb
<!-- <% content_for(:navbar) do %>
  <li><a href="/">Home</a></li>
  <li><%= link_to "Sign In", user_session_path %></li>
  <li><%= link_to "Sign Out", destroy_user_session_path, :method => "delete" %></li>
<% end %> -->

<h2>New Entry</h2>

<%= render "form" %>

app/views/entries/new.js.erb
$('#new_entry_link').hide().after('<%= j render("form") %>')

app/views/entries/show.html.erb
<h2><%= @entry.day %></h2>

<p><%= link_to "Add an Activity", new_entry_activity_path(@entry), id: "new_activity_link", remote: true %></p>


<% if @entry.activities.any? %>
  <h4>Here are the activities for <%= @entry.day %></h4>

  <ul>
    <% @entry.activities.each do |activity| %>
      <li>
        <%= activity.step %> |
        <%= activity.calorie %> |
        <%= activity.minute %> |
        <%= link_to "Edit Activity", edit_entry_activity_path(@entry, activity), id: "edit_activity_link", remote: true %>
        <%= link_to "Delete Activity", entry_activity_path(@entry, activity), :data => {:confirm => "Are you sure you want to delete this activity?", :method => "delete"} %>
      </li>
      <% end %>
  </ul>
<% else %>
  <p>There are no activities yet!</p>
<% end %>

<hr>
<p><%= link_to "Add a Food", new_entry_food_path(@entry), id: "new_food_link", remote: true %></p>

<% if @entry.foods.any? %>
  <h4>Here are the meals for <%= @entry.day %></h4>

  <ul>
    <% @entry.foods.each do |food| %>
      <li>
        <%= food.item %> |
        <%= food.calorie %> |
        <%= food.measurment %> |
        <%= link_to "Edit Food", edit_entry_food_path(@entry, food), id: "edit_food_link", remote: true %>
        <%= link_to "Delete Food", entry_food_path(@entry, food), :data => {:confirm => "Are you sure you want to delete this food?", :method => "delete"} %>
      </li>
      <% end %>
  </ul>
<% else %>
  <p>There are no foods yet!</p>
<% end %>

<hr>
<p>
  <%= link_to "Edit Entry", edit_entry_path(@entry), id: "edit_entry_link", remote: true %>
</p>
<p><%= link_to "Delete Entry", entry_path(@entry), :data => {:confirm => "Are you sure you want to delete this entry?", :method => "delete"} %></p>
<p>
  <%= link_to "Return to Entries", entries_path %>
</p>

app/views/foods/_form.html.erb
<%= render('layouts/errors', :object => @food) %>

<%= form_for [@entry, @food], remote: true do |f| %>
  <%= f.label :item %>
  <%= f.text_field :item, class: "form-control"  %>
  <%= f.label :calorie %>
  <%= f.number_field :calorie, class: "form-control"  %>
  <%= f.label :measurment %>
  <%= f.text_field :measurment, class: "form-control"  %>
  <br>
  <p><%= f.submit class: "btn btn-primary" %></p>
<% end %>

app/views/foods/edit.html.erb
<h1>Edit Food</h1>

<%= render "form" %>

app/views/foods/edit.js.erb
$("#edit_food_link").hide().after("<%= j render('form') %>")

app/views/foods/new.html.erb
<h2>New food for <%= @entry.day %></h2>

<%= render 'form' %>

app/views/foods/new.js.erb
$("#new_food_link").hide().after("<%= j render('form') %>")

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <div class="container">
    <div class="nav">
      <% if user_signed_in? %>
      <%= link_to "Logout", destroy_user_session_path, method: 'delete'  %>
      <% else %>
      <%= link_to "Login", new_user_session_path  %>
      <% end %>
    </div>
    <body>
      <%= flash[:alert] %>
      <%= flash[:notice] %>

      <%= yield %>
    </body>
  </div>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>